import type { RawComment } from '@kanopee/react';

const now = Date.now();
const min = 60_000;
const hr = 60 * min;
const day = 24 * hr;

export const SEED_COMMENTS: RawComment[] = [
  // ── Root ─────────────────────────────────────────────────────
  {
    id: '1',
    parentId: null,
    author: 'Ada Lovelace',
    avatarUrl: 'https://i.pravatar.cc/64?u=ada',
    body: 'The Analytical Engine weaves algebraic patterns, just as the Jacquard loom weaves flowers and leaves. I wonder if we will ever truly understand the implications of what we are building.',
    timestamp: new Date(now - 3 * day).toISOString(),
    likeCount: 42,
    isLiked: false,
  },
  {
    id: '2',
    parentId: '1',
    author: 'Charles Babbage',
    avatarUrl: 'https://i.pravatar.cc/64?u=charles',
    body: "I'm particularly interested in the notion of the engine operating on its own outputs. The recursive potential is staggering.",
    timestamp: new Date(now - 2 * day - 5 * hr).toISOString(),
    likeCount: 18,
    isLiked: true,
  },
  {
    id: '3',
    parentId: '2',
    author: 'Ada Lovelace',
    avatarUrl: 'https://i.pravatar.cc/64?u=ada',
    body: 'Precisely. And yet the engine itself has no opinion on what it computes — that responsibility remains entirely with the operator.',
    timestamp: new Date(now - 2 * day - 3 * hr).toISOString(),
    likeCount: 9,
    isLiked: false,
  },
  {
    id: '4',
    parentId: '3',
    author: 'George Boole',
    body: 'This reminds me of the laws of thought — logic reduced to algebra. Perhaps the engine is the first true mechanical reasoner.',
    timestamp: new Date(now - 2 * day - 1 * hr).toISOString(),
    likeCount: 7,
    isLiked: false,
  },
  {
    id: '5',
    parentId: '4',
    author: 'Ada Lovelace',
    avatarUrl: 'https://i.pravatar.cc/64?u=ada',
    body: 'A mechanical reasoner without reason. The distinction matters greatly.',
    timestamp: new Date(now - 1 * day - 20 * hr).toISOString(),
    likeCount: 14,
    isLiked: false,
  },
  {
    id: '6',
    parentId: '2',
    author: 'Alan Turing',
    avatarUrl: 'https://i.pravatar.cc/64?u=alan',
    body: 'Nearly a century later I found myself asking: can a machine think? I suspect Ada already had the answer.',
    timestamp: new Date(now - 1 * day - 10 * hr).toISOString(),
    likeCount: 31,
    isLiked: false,
  },
  {
    id: '7',
    parentId: '6',
    author: 'Claude Shannon',
    avatarUrl: 'https://i.pravatar.cc/64?u=claude',
    body: "The question might be reframed: not whether it thinks, but whether the output of its processing is indistinguishable from thought.",
    timestamp: new Date(now - 22 * hr).toISOString(),
    likeCount: 22,
    isLiked: false,
  },
  {
    id: '8',
    parentId: '7',
    author: 'Alan Turing',
    avatarUrl: 'https://i.pravatar.cc/64?u=alan',
    body: 'That is, in essence, the test I proposed. Though I remain uncertain it settles the philosophical question.',
    timestamp: new Date(now - 18 * hr).toISOString(),
    likeCount: 11,
    isLiked: false,
  },

  // ── Second root ───────────────────────────────────────────────
  {
    id: '9',
    parentId: null,
    author: 'Grace Hopper',
    avatarUrl: 'https://i.pravatar.cc/64?u=grace',
    body: "The most dangerous phrase in any language is \"we've always done it this way.\" That's how we end up with compilers nobody thought were possible.",
    timestamp: new Date(now - 1 * day - 2 * hr).toISOString(),
    likeCount: 88,
    isLiked: true,
  },
  {
    id: '10',
    parentId: '9',
    author: 'Donald Knuth',
    avatarUrl: 'https://i.pravatar.cc/64?u=donald',
    body: "Premature optimisation is the root of all evil — but premature pessimism about what's possible is nearly as dangerous.",
    timestamp: new Date(now - 20 * hr).toISOString(),
    likeCount: 55,
    isLiked: false,
  },
  {
    id: '11',
    parentId: '10',
    author: 'Grace Hopper',
    avatarUrl: 'https://i.pravatar.cc/64?u=grace',
    body: 'Exactly. Ship something. Measure it. Optimise the parts that matter. In that order.',
    timestamp: new Date(now - 16 * hr).toISOString(),
    likeCount: 33,
    isLiked: false,
  },
  {
    id: '12',
    parentId: '9',
    author: 'Linus Torvalds',
    avatarUrl: 'https://i.pravatar.cc/64?u=linus',
    body: 'Talk is cheap. Show me the code.',
    timestamp: new Date(now - 14 * hr).toISOString(),
    likeCount: 120,
    isLiked: false,
  },
  {
    id: '13',
    parentId: '12',
    author: 'Grace Hopper',
    avatarUrl: 'https://i.pravatar.cc/64?u=grace',
    body: 'Fair point. Though a good README has saved more projects than any amount of clever code.',
    timestamp: new Date(now - 10 * hr).toISOString(),
    likeCount: 47,
    isLiked: false,
  },

  // ── Third root ────────────────────────────────────────────────
  {
    id: '14',
    parentId: null,
    author: 'Margaret Hamilton',
    avatarUrl: 'https://i.pravatar.cc/64?u=margaret',
    body: "Software engineering isn't just about writing code — it's about building systems that don't fail when humans inevitably make mistakes.",
    timestamp: new Date(now - 6 * hr).toISOString(),
    likeCount: 64,
    isLiked: false,
  },
  {
    id: '15',
    parentId: '14',
    author: 'Edsger Dijkstra',
    avatarUrl: 'https://i.pravatar.cc/64?u=edsger',
    body: 'Testing can only show the presence of bugs, never their absence. Correctness must be proven, not merely tested.',
    timestamp: new Date(now - 4 * hr).toISOString(),
    likeCount: 39,
    isLiked: false,
  },
  {
    id: '16',
    parentId: '15',
    author: 'Margaret Hamilton',
    avatarUrl: 'https://i.pravatar.cc/64?u=margaret',
    body: "When you're writing the guidance software for a Moon landing, that distinction becomes very concrete very fast.",
    timestamp: new Date(now - 3 * hr).toISOString(),
    likeCount: 71,
    isLiked: true,
  },
  {
    id: '17',
    parentId: '16',
    author: 'Edsger Dijkstra',
    body: 'Indeed. The Apollo program remains one of the finest arguments for formal methods ever produced.',
    timestamp: new Date(now - 2 * hr).toISOString(),
    likeCount: 28,
    isLiked: false,
  },
  {
    id: '18',
    parentId: '14',
    author: 'Barbara Liskov',
    avatarUrl: 'https://i.pravatar.cc/64?u=barbara',
    body: "Abstractions that compose predictably are the foundation. If a subtype can surprise you, the abstraction has already failed.",
    timestamp: new Date(now - 1 * hr).toISOString(),
    likeCount: 19,
    isLiked: false,
  },
  {
    id: '19',
    parentId: '18',
    author: 'Margaret Hamilton',
    avatarUrl: 'https://i.pravatar.cc/64?u=margaret',
    body: 'Surprises in production are exactly what we are trying to eliminate. Predictability over cleverness, every time.',
    timestamp: new Date(now - 30 * min).toISOString(),
    likeCount: 12,
    isLiked: false,
  },
  {
    id: '20',
    parentId: null,
    author: 'Bjarne Stroustrup',
    avatarUrl: 'https://i.pravatar.cc/64?u=bjarne',
    body: 'C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do it blows your whole leg off.',
    timestamp: new Date(now - 15 * min).toISOString(),
    likeCount: 200,
    isLiked: false,
  },
];
